server:
  port: 8080

printer:
  enabled: true

spring:
  application:
    name: my-client
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8080
        url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"